### ISSUE TITLE
Mocking BrowserWindow

### ISSUE THREAD

**Issue by pezholio** [jprichardson/electron-mocha#64] opened 2016-05-20 09:46 UTC
Hi, 

I'm using electron-mocha to test my electron app, and am having trouble using [Sinon](http://sinonjs.org/) to stub a `BrowserWindow` instance to test against. My code looks like this:

Application Code:
```
var loadWindow = function(myWindow, apiKey) {
  myWindow.loadURL('file://' + __dirname + '/../views/auth.html')
  myWindow.webContents.on('dom-ready', function() {
    myWindow.webContents.send('apiKey', apiKey)
  })
}
```

Test
```
it('loads the window', function() {
   myWindow = sinon.createStubInstance(BrowserWindow)
   github._private.loadWindow(myWindow, "bogus-key")
   expect(myWindow.calledWith('file://' + __dirname + '/../views/auth.html')).to.eq(true)
})
```

When I run my tests I get:
```
  1) loadWindow loads the window:
     Error: Object has been destroyed
      at Error (native)
      at node_modules/sinon/lib/sinon/walk.js:28:50
      at Array.forEach (native)
      at walkInternal (node_modules/sinon/lib/sinon/walk.js:23:45)
      at walkInternal (node_modules/sinon/lib/sinon/walk.js:34:17)
      at Object.walk (node_modules/sinon/lib/sinon/walk.js:49:20)
      at Object.stub (node_modules/sinon/lib/sinon/stub.js:52:23)
      at Object.sinon.createStubInstance (node_modules/sinon/lib/sinon/util/core.js:361:26)
      at Context.<anonymous> (app/test/main/github_spec.js:74:24)
```

Any ideas where I might be going wrong?

**Comment by inukshuk** [comment] 2016-05-20 12:54
Is this on Electron 1.1 and has it worked previously? I had previously inherited from `BrowserWindow` and noticed a few issues when upgrading to 1.1 (some parts of `BrowserWindow` are native bindings, I believe, so it might be that there's something that there that Sinon can't hook into -- a quick workaround would be to write your own stub object).

We've recently started destroying windows, but only after the tests have run and since the error happens in `createStubInstance` I don't think this is being caused by electron-mocha.

**Comment by pezholio** [comment] 2016-05-20 15:56
No, I've never been able to get it to work - I've just upgraded from `0.3.x` just to see if that helped, but I still get the same error.

**Comment by inukshuk** [comment] 2016-05-23 12:46
I'll close this for now as this isn't an electron-mocha issue.

@pezholio I suggest that you create your own window stub for now. There is something about the BrowserWindow prototype's native binding that's throwing off Sinon here. You will probably get the same Error if you try to inspect the prototype yourself -- Sinon obviously runs into the same issue when walking the prototype for stubs to create.

**Closed by inukshuk** 2016-05-23 12:46 UTC
