### ISSUE TITLE
Bunch of "undefined" printed to stdout

### ISSUE THREAD

**Issue by grenierdev** [jprichardson/electron-mocha#150] opened 2019-10-27 15:09 UTC
- Windows 10
- Node v12.13.0
- NPM v6.12.0
- Electron v6.0.9
- Electron-Mocha v8.1.2
- Mocha v6.2.1
- Chai v4.2.0

I'm having a bunch of `undefined` in my stdout.

```
> pxlr@1.0.0 test:renderer [...redacted...]
> electron-mocha --renderer --require ts-node/register tests/**/*.spec.renderer.ts


undefined

  Boop
    √ works (81ms)
undefined
undefined
  1 passing (89ms)
undefined
```

My code doe not use any console call. Here's the source.

```ts
import 'mocha';
import { expect } from 'chai';
import { nativeImage } from 'electron';
import { readFileSync } from 'fs';

describe('Boop', () => {
	it('works', async () => {
		const canvas = document.createElement('canvas');
		canvas.width = 128;
		canvas.height = 128;
		const gl = canvas.getContext('webgl')!;
		gl.clearColor(0, 0, 1, 1);
		gl.clearDepth(1);
		gl.clear(gl.COLOR_BUFFER_BIT | gl.DEPTH_BUFFER_BIT);

		const dataURL = canvas.toDataURL('image/png');
		const img = nativeImage.createFromDataURL(dataURL);
		const canvasBuffer = img.toPNG();

		const testPNG = await readFileSync(__dirname + '/boop.png');
		expect(canvasBuffer).to.eql(testPNG);
	});
});
```

**Comment by inukshuk** [comment] 2019-10-28 09:04
Seems to be a Windows issue. The undefined [show up in our tests as well](https://ci.appveyor.com/project/jprichardson/electron-mocha); on macOS and Linux they show up as empty new lines. It's happening without `--renderer` too, so it's not caused by the way we forward the output to the main process.

**Comment by grenierdev** [comment] 2019-11-01 02:23
Your right. I'm not seeing them in my CI tests (Linux docker).

**Comment by pdamasceno** [comment] 2019-11-05 23:22
Any news on when or if this is going to be fixed?
Seeing the same behaviour on the tests here.
Not a major issue, but annoying nonetheless.

**Comment by ChrisHSandN** [comment] 2019-11-21 13:18
To add some (hopefully) useful info I found while debugging where this comes from:

The first shown `undefined` comes from: `node_modules/mocha/lib/reporters/spec.js`
```
  runner.on(EVENT_RUN_BEGIN, function() {
    Base.consoleLog();
  });
```
- Changing `Base.consoleLog()` to `Base.consoleLog('')` makes the `undefined` go away
- If I run the same command which `electron-mocha` spawns:
`node_modules\electron\dist\electron.exe node_modules/electron-mocha/lib/main.js temp/spec-main.js`
The `undefined` is shown (so it doesn't seem to be to do with the spawning/piping of stdout etc.)

**Comment by Tobias-Keller** [comment] 2019-12-18 11:27
> 
> 
> To add some (hopefully) useful info I found while debugging where this comes from:
> 
> The first shown `undefined` comes from: `node_modules/mocha/lib/reporters/spec.js`
> 
> ```
>   runner.on(EVENT_RUN_BEGIN, function() {
>     Base.consoleLog();
>   });
> ```
> 
>     * Changing `Base.consoleLog()` to `Base.consoleLog('')` makes the `undefined` go away
> 
>     * If I run the same command which `electron-mocha` spawns:
>       `node_modules\electron\dist\electron.exe node_modules/electron-mocha/lib/main.js temp/spec-main.js`
>       The `undefined` is shown (so it doesn't seem to be to do with the spawning/piping of stdout etc.)

there are also some Base.consoleLog(); in this fiele:
node_modules/mocha/lib/reporters/base.js

if we add '' to this, all undefines are away

**Comment by inukshuk** [comment] 2019-12-18 20:34
@ChrisHSandN @Tobias-Keller thanks for digging into this. I think this is probably something we need to address in Electron (or workaround it by patching in Electron-Mocha). You can easily reproduce this with Electron on Windows with `npx electron test.js` and `test.js` something like:

     console.log('---')
     console.log()
     console.log('')
     console.log('---')
     require('electron').app.quit()

On Linux this prints two blank lines between the markers with Electron and Node.js. Glancing briefly at [the spec](https://console.spec.whatwg.org/#logger) I actually think this should be only a single blank line? Maybe not, though, since pretty much everything I looked at prints two blank lines.

Except Electron on Windows, which prints `undefined` instead of the first blank line. Would be good to know why?

Anyway, it should be trivial to work around if we want to. We can just replace `console.log` before require any modules. Something like `console.log = (first = '', ...rest) => originalConsoleLog(first, ...rest)` should probably do it.

**Comment by inukshuk** [comment] 2020-07-07 13:41
I'll close this because our tests on AppVeyor don't expose this behavior anymore in the latest version.

**Closed by inukshuk** 2020-07-07 13:41 UTC
